### ISSUE TITLE
vsetv.com-grabber

### ISSUE THREAD

**Issue by omtelecom** [quarckster/vsetv.com-grabber#1]
Здравствуйте
призапусте вывет ошибок
python vsetvcom_grabber.py -u user -p passwd

Traceback (most recent call last):
  File "vsetvcom_grabber.py", line 111, in <module>
    write(parse_args()[2])
  File "vsetvcom_grabber.py", line 101, in write
    w.write(file)
  File "/usr/lib/python2.7/dist-packages/xmltv.py", line 566, in write
    et.write(file)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 821, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 940, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 940, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 938, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1074, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 2: ordinal not in range(128)
создает tv_guide.xml
содержимое 
cat tv_guide.xml
<tv><channel id="1"><display-name lang="ru">
не пишу на питоне, посему трудновато пока понять в чем причина ((
Вас не затрудник помочь ?

Спасибо

**Comment by quarckster** [comment]
Используйте python3
