### ISSUE TITLE
vsetvcom_grabber.py

### ISSUE THREAD

**Issue by linoobs** [quarckster/vsetv.com-grabber#3]
Добрый вечер, обнаружил что уже несколько дней не работает парсер, причем на двух разных машинах с одинаковой проблемой:
`Traceback (most recent call last):
  File "/home/a/vsetv/vsetvcom_grabber.py", line 111, in <module>
    write(parse_args()[2])
  File "/home/a/vsetv/vsetvcom_grabber.py", line 99, in write
    for i in make_dict():
  File "/home/a/vsetv/vsetvcom_grabber.py", line 85, in make_dict
    correct_starttime(),
  File "/home/a/vsetv/vsetvcom_grabber.py", line 52, in correct_starttime
    starttime_lists = [list(map(dt, p)) for p in get_starttime()]
  File "/home/a/vsetv/vsetvcom_grabber.py", line 50, in <lambda>
    dt = lambda st: datetime.combine(date.today(), time(int(st.split(":")[0]),
ValueError: invalid literal for int() with base 10: ''

`

**Comment by quarckster** [comment]
Fixed in a469f43
